/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.solace.aaron.log4j2.appender;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
